### ISSUE TITLE
Feature request: Support Debian Bookworm with Debian-12.yml

### ISSUE THREAD

**Issue by shk3bq4d** [juju4/ansible-ipv6#10]
### Detailed Description

Hello,

Same request as #7, but for Debian 12 instead of Debian 11

Have an excellent day! :-)

### Possible Implementation

duplicate vars/Debian-11.yml to vars/Debian-12.yml with all same content

I don't masterize neither version of Debian, but at least this made the role execution succeed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juju4** [comment]
Done
