### ISSUE TITLE
role does not disable ipv6 on Ubuntu 18.04.3 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by kmonticolo** [juju4/ansible-ipv6#2]
ansible 2.8.2
python version = 2.7.5

It helps when I changed two lines in /etc/default/grub to:
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"
GRUB_CMDLINE_LINUX="ipv6.disable=1"

and invoke update-grub and reboot

**Comment by juju4** [comment]
Sorry for delayed answer.
How do you test ipv6 is disabled?

from https://github.com/juju4/ansible-ipv6/blob/master/tasks/ipv6-disable.yml
it should be disabled at sysctl level, at kernel modules/modprobe and redhat sysconfig/network.

I just added an option for grub command line + extra testing but should not change outcome.

**Comment by kmonticolo** [comment]
I invoked "ip a" and searched for an ipv6 address.

czw., 29 sie 2019, 16:30 użytkownik Julien <notifications@github.com>
napisał:

**Comment by holmesb** [comment]
I'm seeing this too.  I run this role on ubuntu 18.04 and ip a reports IPv6 configuration is still present.  Unless I'm mistaken, this role changes /etc/sysctl.conf without enacting the change with a `sysctl -p`.

Or in the case of ansible's sysctl module, with a `reload: true`.   This role only disables IPv6 after a reboot.

**Comment by juju4** [comment]
Fine for the patch.
Just keep in mind role is disabling ipv6 through multiple options (sysctl, module blacklist, grub) and things like grub can only apply with a reboot
